name: ige
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - selenium
    - webdriver-manager
    - pandas
    - openpyxl
    - PyPDF2
    - python-dotenv
    - requests
    - beautifulsoup4
    - streamlit